dist: trusty

os: linux

language: php

notifications:
  email:
    recipients:
      - plugins@cleantalk.org
    on_failure: never
    on_success: never

jobs:
  include:
    - env: TRAVISCI=phpunit
    - env: TRAVISCI=phpcs
    - env: TRAVISCI=psalm

before_script:
  - |
    if [[ "$TRAVISCI" == "phpunit" ]] ; then
      composer require phpunit/phpunit 7.*
    fi
  - |
    if [[ "$TRAVISCI" == "phpcs" ]] ; then
      composer require squizlabs/php_codesniffer
      composer require phpcompatibility/php-compatibility
      vendor/bin/phpcs --config-set installed_paths vendor/phpcompatibility/php-compatibility
    fi
  - |
    if [[ "$TRAVISCI" == "psalm" ]] ; then
      source tests/wp-test-setup.sh
      composer require vimeo/psalm
      composer require humanmade/psalm-plugin-wordpress
      composer require php-stubs/wordpress-stubs

    fi

script:
  - |
    if [[ "$TRAVISCI" == "phpunit" ]] ; then
      vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-text
    fi
  - |
    if [[ "$TRAVISCI" == "phpcs" ]] ; then
      vendor/bin/phpcs --standard=tests/.phpcs.xml
    fi
  - |
    if [[ "$TRAVISCI" == "psalm" ]] ; then
      vendor/bin/psalm --no-cache --config=psalm.xml
    fi